### ISSUE TITLE
Limit the destruction potential of `RxJournal#cleanCache`

### ISSUE THREAD

**Issue by simonbasle** [danielshaya/rxjournal#2]
This currently deletes the whole content of the RxJournal folder, and the folder itself.
IMHO it is too easy to create an `RxJournal` pointing to an existing folder and then obliterate it with that method. To make this scenario less likely, several steps can be taken:
 - better document the RxJournal constructor and `clearCache` method to indicate it destroys the directory
 - limit the `clearCache` to deleting **files** inside the directory (and not subdirectories nor the directory itself)
 - limit the deletion of files to `*.cq4` files, aka only delete binary files from `ChronicleQueue`
 - maybe use the given directory as a "base directory for temporary files" and create a **dedicated subdir** instead of using it as is. That subdir would then be the only one obliterated.

**Comment by danielshaya** [comment]
Thanks these are all great suggestions.

Btw happy to accept any pull requests you want to make on this although as you know the code is still in a state of flux :)
